export default [
        {
        art: '/static/images/art/at-2501a.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Project 2501a',
        printSize: '20x16',
        id: '2501a',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-2501b.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Project 2501b',
        printSize: '20x16',
        id: '2501b',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-bladerunner1.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'BladeRunner Poster 1',
        printSize: '20x16',
        id: 'br1',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-bladerunner2.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'BladeRunner Poster 2',
        printSize: '20x16',
        id: 'br2',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-lostboy1.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Lost Boys Poster 1',
        printSize: '20x16',
        id: 'lb1',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'yes',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-lostboy2.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Lost Boys Poster 2',
        printSize: '20x16',
        id: 'lb2',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'yes',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-lostboy3.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Lost Boys Poster 3',
        printSize: '20x16',
        id: 'lb3',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'yes',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-lostboy4.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Lost Boys Poster 4',
        printSize: '20x16',
        id: 'lb4',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'yes',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-lostboy5.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Lost Boys Poster 5',
        printSize: '20x16',
        id: 'lb5',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'yes',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo1.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 1',
        printSize: '20x16',
        id: 'geo1',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo2.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 2',
        printSize: '20x16',
        id: 'geo2',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo3.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 3',
        printSize: '20x16',
        id: 'geo3',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo4.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 4',
        printSize: '20x16',
        id: 'geo4',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo5.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 5',
        printSize: '20x16',
        id: 'geo5',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo6.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 6',
        printSize: '20x16',
        id: 'geo6',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo7.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Geo 7',
        printSize: '20x16',
        id: 'geo7',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo8.jpg',
        shape: 'square',
        detailShape: 'detailViewImg-square',
        title: 'Geo 8',
        printSize: '20x16',
        id: 'geo8',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo9.jpg',
        shape: 'square',
        detailShape: 'detailViewImg-square',
        title: 'Geo 9',
        printSize: '20x16',
        id: 'geo9',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-geo10.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Geo 10',
        printSize: '20x16',
        id: 'geo10',
        price: 16,
        ashthorp: 'no',
        geo: 'yes',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch1.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 1',
        printSize: '20x16',
        id: 'epoch1',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch2.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 2',
        printSize: '20x16',
        id: 'epoch2',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch3.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 3',
        printSize: '20x16',
        id: 'epoch3',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch4.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 4',
        printSize: '20x16',
        id: 'epoch4',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch5.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 5',
        printSize: '20x16',
        id: 'epoch5',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/at-epoch6.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Epoch Poster 6',
        printSize: '20x16',
        id: 'epoch6',
        price: 16,
        ashthorp: 'yes',
        geo: 'no',
        infra: 'no',
        gmunk: 'no',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra2.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 2',
        printSize: '20x16',
        id: 'infra2',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra3.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 3',
        printSize: '20x16',
        id: 'infra3',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra4.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 4',
        printSize: '20x16',
        id: 'infra4',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra5.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 5',
        printSize: '20x16',
        id: 'infra5',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra6.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 6',
        printSize: '20x16',
        id: 'infra6',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra7.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 7',
        printSize: '20x16',
        id: 'infra7',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra8.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 8',
        printSize: '20x16',
        id: 'infra8',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra9.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Infra Photo 9',
        printSize: '20x16',
        id: 'infra9',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra10.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 10',
        printSize: '20x16',
        id: 'infra10',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra11.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Infra Photo 11',
        printSize: '20x16',
        id: 'infra11',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra12.jpg',
        shape: 'tall',
        detailShape: 'detailViewImg-tall',
        title: 'Infra Photo 12',
        printSize: '20x16',
        id: 'infra12',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-infra13.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Infra Photo 13',
        printSize: '20x16',
        id: 'infra13',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'yes',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-op1.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Op Art 1',
        printSize: '20x16',
        id: 'op1',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-op2.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Op Art 2',
        printSize: '20x16',
        id: 'op2',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
        {
        art: '/static/images/art/g-op3.jpg',
        shape: 'wide',
        detailShape: 'detailViewImg-wide',
        title: 'Op Art 3',
        printSize: '20x16',
        id: 'op3',
        price: 16,
        ashthorp: 'no',
        geo: 'no',
        infra: 'no',
        gmunk: 'yes',
        lostboy: 'no',
        quantity: 0,
        },
    ]